version: "3.8"

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vue_frontend
    container_name: vue_frontend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    depends_on:
      - app

  node:
    platform: linux/arm64/v8
    build:
      context: ./frontend
      dockerfile: Dockerfile.node
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
      - /var/www/node_modules
    networks:
      - app-network
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: roster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
