version: "3.8"

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_DATABASE=roster
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: vue_app
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - app

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: roster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
